# Generated by Django 5.2.3 on 2025-07-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('prep_time', models.IntegerField(blank=True, null=True)),
                ('cook_time', models.IntegerField(blank=True, null=True)),
                ('total_time', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('nutrients', models.TextField()),
                ('serves', models.CharField(max_length=100)),
            ],
        ),
    ]
